# makes the container available to peer services
# NOT available as a standalone service as constituted;
version: '2'
services:
  keystone:
    build: .
    image: styers/keystone:extended-list-query
    container_name: keystone
