# makes the container available to peer services
# NOT available as a standalone service as constituted;
version: '2'
services:
  keystone:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    image: styers/keystone:edge-extended-list
    container_name: keystone
