# uses an alpine linux image with node/npm pre-installed
FROM mhart/alpine-node:6.9.1

# adds current directory to image at /app/keystone
ADD . /keystone

# issues some final instructions to prep for build
# on build, the working directory will be /app/keystone
WORKDIR /keystone

# on build, /app/keystone on this image (i.e. this directory) will
# be mapped to the dependent image at the same location
VOLUME /keystone

# adds some instuctions to execute at the beginning of the dependant image's
# build process.
# At build time, we'll pull down the minimum system modules required to execute
# keystone's pre/post install scripts. Then, we'll install keystone and create a
# link we reference when building the dependant image.
ONBUILD RUN apk add --no-cache make gcc g++ python && npm i && npm link
